version: '3'
services:
  app:
    container_name: wic_task
    restart: always
    build: .
    ports:
      - '5000:3000'
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6380:6379"
    hostname: redis
